name: zt_totp_mobile
description: ZT-TOTP mobile authenticator prototype.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  mobile_scanner: ^7.1.4
  crypto: ^3.0.3
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
